name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java 22
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      # Step 3: Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      # Step 4: Install dependencies (optional, if you still want to install dependencies but skip tests)
      - name: Install Dependencies
        run: mvn clean install -DskipTests

      # Step 5: Run SonarQube Analysis
      - name: SonarCloud Analysis
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=muraliraghu7_SeleniumJavaFrameworkSonarAssessment \
            -Dsonar.organization=murali-raghupathy \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
