name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java 22
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      # Step 3: Install Maven
      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      # Step 4: Install dependencies
      - name: Install Dependencies
        run: mvn clean install -DskipTests

      # Step 5: Run SonarQube Analysis
      - name: SonarCloud Analysis
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=muraliraghu7_SeleniumJavaFrameworkSonarAssessment \
            -Dsonar.organization=murali-raghupathy \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Step 6: Fetch SonarCloud Metrics and Issues
      - name: Fetch SonarCloud Metrics and Issues
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/measures/component?componentKey=muraliraghu7_SeleniumJavaFrameworkSonarAssessment&metricKeys=bugs,vulnerabilities,code_smells,coverage" > sonar-metrics.json
          curl -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/issues/search?componentKeys=muraliraghu7_SeleniumJavaFrameworkSonarAssessment&resolved=false" > sonar-issues.json
          cat sonar-metrics.json
          cat sonar-issues.json

      # Step 7: Generate a Report
      - name: Generate Sonar Report
        run: |
          npm install axios
          node -e "
          const fs = require('fs');
          const metrics = require('./sonar-metrics.json');
          const issues = require('./sonar-issues.json');
          const timestamp = new Date().toLocaleString();

          let report = '<html><head><title>SonarQube Report</title>';
          report += '<style>body { font-family: Arial; }</style></head><body>';
          report += '<h1>SonarQube Analysis Report</h1>';
          report += \`<p><strong>Generated on:</strong> \${timestamp}</p>\`;

          if (metrics.component) {
            report += '<h2>Metrics</h2>';
          } else {
            report += '<h2>No Metrics</h2>';
          }

          fs.writeFileSync('sonar-report.html', report);
          console.log('Report generated.');
          "
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          mv sonar-report.html sonar-report-${TIMESTAMP}.html

      # Step 8: Upload the Report
      - name: Upload Sonar Report
        uses: actions/upload-artifact@v4
        with:
          name: sonar-report
          path: sonar-report-*.html
